### PR TITLE
Es2015 convert

### PR DESCRIPTION
**Pull request by yuchi**
You are obviously free to trash this PR, but if you had in mind to switch to ES2015 I made it for you.

### CODE REVIEW

**Comment by robframpton** [comment]
Hey @yuchi 

I wasn't planning on doing it soon, but since you already did the work :)

I'll probably take a look at this pull sometime next week.

**Comment by yuchi** [comment]
Just curious, do you plan to merge this? :)

**Comment by robframpton** [comment]
I wasn't planning on converting it soon, is this a blocker for you?

**Comment by yuchi** [comment]
No, just an open item in my never ending list.

**Comment by robframpton** [comment]
Alrighty, I'll go ahead and close this and reopen it when it comes time. Thanks, @yuchi

**Comment by yuchi** [comment]
`¯\_(ツ)_/¯`

**Comment by yuchi** [comment]
Is it time? 😂

**Pull request closed without merging**
